# Generated by Django 2.2.10 on 2020-02-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0002_auto_20200214_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(null=True, upload_to='archivos/%Y/%m/%d')),
                ('IDInmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inmueble.Inmueble')),
            ],
        ),
    ]
