# Generated by Django 2.2.10 on 2020-02-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_auto_20200223_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
