# Generated by Django 2.2.10 on 2020-02-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0006_auto_20200223_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
