# Generated by Django 2.2.10 on 2020-03-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0008_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='ruta',
            field=models.ImageField(null=True, upload_to='imagenes/%Y/%m/%d'),
        ),
    ]
