# Generated by Django 2.2.10 on 2020-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0009_auto_20200326_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/%Y/%m/%d'),
        ),
    ]
