# Generated by Django 2.2.10 on 2020-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0011_auto_20200408_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/%Y/%m/%d'),
        ),
    ]
