# Generated by Django 2.2.10 on 2020-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0013_auto_20200411_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
