# Generated by Django 2.2.10 on 2020-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0014_auto_20200411_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='asunto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='mensaje',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
