# Generated by Django 2.2.10 on 2020-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0015_auto_20200414_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
