# Generated by Django 2.2.10 on 2020-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0018_inmueble_imagenppal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AlterField(
            model_name='cita',
            name='inmueble',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
