# Generated by Django 2.2.10 on 2020-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0020_auto_20200428_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
