# Generated by Django 2.2.10 on 2020-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0021_auto_20200428_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
