# Generated by Django 2.2.10 on 2020-05-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0022_inmueble_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mensajedos',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
