# Generated by Django 2.2.10 on 2020-05-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0023_cita_mensajedos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='mensajedos',
        ),
    ]
