# Generated by Django 2.2.10 on 2020-02-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='per_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Rol'),
        ),
    ]
