# Generated by Django 2.2.10 on 2020-02-14 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200213_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='per_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
