# Generated by Django 2.2.10 on 2020-02-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200213_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='per_user',
            new_name='IDUser',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='per_rol',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='rol_nombre',
        ),
        migrations.AddField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
