# Generated by Django 2.2.10 on 2020-02-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200219_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='IDRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuario.Rol'),
            preserve_default=False,
        ),
    ]
